# en_fa_data.yaml

## Where the samples will be written
save_data: en_fa_data/run/example
## Where the vocab(s) will be written
src_vocab: en_fa_data/run/example.vocab.src
tgt_vocab: en_fa_data/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

# Corpus opts:
data:
    corpus_1:
        path_src: en_fa_data/fa_train.txt
        path_tgt: en_fa_data/en_train.txt
    valid:
        path_src: en_fa_data/fa_val.txt
        path_tgt: en_fa_data/en_val.txt


# Vocabulary files that were just created
src_vocab: en_fa_data/run/example.vocab.src
tgt_vocab: en_fa_data/run/example.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: en_fa_data/run/model
save_checkpoint_steps: 500
train_steps: 1000
valid_steps: 500